version: '3'

services:
  rxdb:
    container_name: authordb
    image: local_rxdbthing
    environment:
    - POSTGRES_PASSWORD=
    links:
    - pgadmin
    ports:
    - "0.0.0.0:5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
    - PGADMIN_DEFAULT_EMAIL=postgres
    - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./:/var/lib/pgadmin/storage/postgres/
